### ISSUE TITLE
jekyll version dependency upgrade? (current clash with jekyll-scholar)

### ISSUE THREAD

**Issue by mshadbolt** [ELIXIR-Belgium/elixir-toolkit-theme#109]
Hiya

I asked recently about whether there is any advice on using academic citations with the theme. Bert directed me to jekyll-scholar which I was excited to try but unfortunately when I try to set it up, the theme and the plugin have conflicting jekyll dependencies:

```
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    elixir-toolkit-theme was resolved to 1.20.2, which depends on
      jekyll (~> 3.9)

    jekyll-scholar was resolved to 7.1.1, which depends on
      jekyll (~> 4.0)
```

I was wondering if there is any plan to upgrade the dependency for the them to the next major version?

Thanks

**Comment by mshadbolt** [comment]
Ok, I have figured out a work around by using jekyll scholar version 5.16 which depends on jekyll ~>3

But the workflow I am using currently uses github actions to build the site and push to the gh-pages branch, then the website is deployed from that branch. However this causes the gh edit links at the top of each page to break, because they automatically reference the gh-pages branch, rather than the main branch where the markdown docs actually live. I was wondering if you had considered implementing configurable gh links like just the docs does?

see here:
https://github.com/just-the-docs/just-the-docs/blob/b09fd44d7099604d285d112fafe8ac95c742bd61/_config.yml#L125

See here if you would like to see the repo I am currently testing with:
https://github.com/mshadbolt/human-omics-data-sharing-field-guide

And example of bibliography on page with citations https://mshadbolt.github.io/human-omics-data-sharing-field-guide/data_repositories#references

**Comment by mshadbolt** [comment]
hmm I should check things properly first... looked at your config yaml more closely and found the setting to change this and now it works perfectly! 

I leave this open regarding the jekyll versioning as it would be good to stay up to date with latest version of the scholar plugin but am happy it is working for now.

**Comment by bedroesb** [comment]
Hello, https://github.com/mshadbolt/human-omics-data-sharing-field-guide/commit/7174b0f8e3a8b67cfed5c7150555f3040f160ebc#diff-ecec67b0e1d7e17a83587c6d27b6baaaa133f42482b07bd3685c77f34b62d883R24

This should not be needed since this is determined by the GitHub pages setting in the settings. Or did you use GitHub Actions for the deployment?

Nice to see you got scholar working! I did not yet try that!

**Comment by bedroesb** [comment]
We use Font Awesome ourselves, so in theory https://github.com/AustralianBiocommons/human-omics-data-sharing-field-guide/blob/main/pages/data_standards/ga4gh.md?plain=1#L9 is not needed. Nice table Btw!

**Comment by mshadbolt** [comment]
Hi, yes I am using github actions for deployment in order to get scholar to work.

**Comment by bedroesb** [comment]
I think this can be closed than @mshadbolt ? :)
