### ISSUE TITLE
Issue on page: Navigation structure

### ISSUE THREAD

**Issue by BBBiz** [ELIXIR-Belgium/elixir-toolkit-theme#190]
I would like to report an issue on the Navigation structure page at `/navigation_structures`. Description of the issue: how do I make a page not show on the top navigation toolbar?

**Comment by bedroesb** [comment]
Hello! I am actuality in the process of improving the documentation in my latest pull request. You can already read the[ new navigation structures here](https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/blob/doc-update/pages/documentation/navigation_structures.md). Hope this helps!

**Comment by bedroesb** [comment]
The new documentation is now live at https://elixir-belgium.github.io/elixir-toolkit-theme/navigation_structures

**Comment by bedroesb** [comment]
Hope this will sufficiently help you adapting your topnavigation. Don't forget to always start from our  https://github.com/ELIXIR-Belgium/elixir-toolkit-theme-example example and instructions.
