### ISSUE TITLE
Website sections tiles search=false is not effective

### ISSUE THREAD

**Issue by PhilReedData** [ELIXIR-Belgium/elixir-toolkit-theme#253]
When including section-navigation-tiles.html, I get the same results by including search=true and search=false, i.e. the search box shows. When I remove the parameter, I get no search box.

**Comment by PhilReedData** [comment]
I think, but I'm not sure, that this can be fixed by changing two lines in https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/blob/main/_includes/section-navigation-tiles.html

Line 36, {%- unless include.search == nil %}
change to {%- if include.search == true %}

Line 46, {%- endunless %}
change to {%- endif %}

...but I don't know how that affects Line 1, which also has an unless ... include.search == nil

**Comment by bedroesb** [comment]
Hey @PhilReedData indeed, your proposed solution is correct, but line one needs to be adapted as well as you suspected. I opened a pull request that also fixes a wrong description in the doc. Thanks for bringing this to light!
