### ISSUE TITLE
Search feature does not include pages from collections

### ISSUE THREAD

**Issue by elichad** [ELIXIR-Belgium/elixir-toolkit-theme#265]
For an example in deployment, see https://github.com/ResearchObject/ro-crate/issues/336. Our specification pages are in a Jekyll collection within our [repo](https://github.com/ResearchObject/ro-crate/tree/main/docs) (i.e. not under `pages/` but under `_specification`), and they don't show up in search results because of this.

I've had a poke around the search code and I think the problem is here:
https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/blob/main/assets/js/search-data.json#L8

Namely that `site.html_pages` doesn't appear to include pages from collections.

## Possible solution

I found that I could add one extra line to include the missing pages into the search (without duplicating the other pages) - [site.documents](https://jekyllrb.com/docs/variables/#site-variables) provides "A list of all the documents in every collection."
```
...
{%- assign pages_array = "" | split: "" -%}
{%- assign pages_array = pages_array | push: site.html_pages -%}
{%- assign pages_array = pages_array | push: site.documents -%} # this is added
{%- for pages in pages_array -%}
...
```

This will work for our site but I'm not sure if it will work for every site that uses the theme. @bedroesb could you let me know if this is something that you can incorporate in the base theme? If you know of an alternative solution I welcome that too.

**Comment by bedroesb** [comment]
@elichad I've just tested out your proposed solution and it works in the circumstances I can think of, so for me it is fine to add it to the main theme! Do you make a PR? Than you are better attributed for this fix IMO. Thanks a lot for figguring this out!
