### ISSUE TITLE
"404 not found" item in left hand side navigation

### ISSUE THREAD

**Issue by anenadic** [ELIXIR-Belgium/elixir-toolkit-theme#302]
"404 page not found" item in left hand side navigation - is this intentional to showcase a 404 page? Please close if a non-issue. 

![image](https://github.com/user-attachments/assets/05d8c82f-8ba6-4c68-817e-a38ade3b1b9e)

**Comment by bedroesb** [comment]
@anenadic THis is idneed to showcase the 404 page :) Maybe not the best place. Any suggestions on how to make this more clear?

**Comment by anenadic** [comment]
Huh, not sure @bedroesb. Maybe rename the sidebar navigation title to be "Example 404 Not Found Page" or something? Also please feel to close as a non issue.

**Comment by bedroesb** [comment]
No I like it! let me change it to something alike
