### ISSUE TITLE
RSQKit using the ETT theme - acknowledgement

### ISSUE THREAD

**Issue by anenadic** [ELIXIR-Belgium/elixir-toolkit-theme#306]
[RSQKit](https://github.com/EVERSE-ResearchSoftware/RSQKit) (renders at http://everse.software/RSQKit/) is another site using the great ETT - if you want to add it at https://elixir-belgium.github.io/elixir-toolkit-theme/#this-theme-is-known-to-be-used-in.

**Comment by bedroesb** [comment]
Hey @anenadic I think it is already there? :) 

- [RSQkit: Research Software Quality kit](https://everse.software/RSQKit/) (EOSC-EVERSE)

**Comment by anenadic** [comment]
Oh, it is there indeed. Thank you @bedroesb.
