### ISSUE TITLE
Hanging </div> visible when no contributors found on Editorial Board page

### ISSUE THREAD

**Issue by anenadic** [ELIXIR-Belgium/elixir-toolkit-theme#307]
I noticed a small bug when listing all contributors with "editor" role on Editorial Board page - when the list is empty then perhaps there should not be an empty carousel but a note saying something like "No contributors found". This has nothing to do with filtering contributors by the role btw. - it's just where I noticed the bug.

There is a hanging closing </div> tag which is mistake somewhere in https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/blob/main/_includes/contributor-carousel-selection.html (but I could not figure out which one it is - my suspicion is on the line 47: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/blob/main/_includes/contributor-carousel-selection.html#L47 but it is not as simple as that). 

This hanging </div> tag is only visible on the page when the contributors list is empty - but it is always there just browsers are good at ignoring it.

See the screenshot with issue:

<img width="1973" alt="image" src="https://github.com/user-attachments/assets/d01d9f27-a56b-4ed3-8abd-7437c687761b" />

The hanging </div> tag present even when the contributors list is not empty.

![image](https://github.com/user-attachments/assets/7d6b1890-ae2a-4526-8a6a-ff6b316aa296)

**Comment by bedroesb** [comment]
I broke my brain about the carousel code one more time, I also noticed that in general the role filtering was not implemented well. Could you have a look if the bug is gone using [contr-fix](https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/tree/contr-fix) as branch?

**Comment by anenadic** [comment]
> I broke my brain about the carousel code one more time, I also noticed that in general the role filtering was not implemented well. Could you have a look if the bug is gone using [contr-fix](https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/tree/contr-fix) as branch?

Will do - thank you. That carousel code is a bit complex :-) - I tried simplifying it myself, then had to move onto somethign else. Thanks for looking into it.
